version: 2
jobs:
    build:
        docker:
        - image: circleci/openjdk:8-jdk-browsers
        steps:
        - checkout
        - run: git clone https://github.com/SkyWars/SkyWars-Translations.git
        - run: git clone -b "$CIRCLE_BRANCH" https://github.com/SkyWars/SkyWars-API.git
        - run: (cd SkyWars-Translations && mvn clean install)
        - run: (cd SkyWars-API && mvn clean install)
        - run: mvn clean package test integration-test
        - store_artifacts:
            path: target/SkyWars.jar
            destination: SkyWars.jar
